LaporanKasus/urls.py
from django.urls import path
from LaporanKasus.views import Index, getLaporanKasusUserDetail
from LaporanKasus.views import LaporanKasusUserDetail, LaporanKasusUserUpdate
from LaporanKasus.views import LaporanKasusContinue, LaporanKasusSave
from LaporanKasus.views import LaporanKasusPrint

app_name = 'laporankasus'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path(
        'g/',
        getLaporanKasusUserDetail,
        name='getlaporankasususer-detail'),
    path(
        'd/<uuid:pk>/',
        LaporanKasusUserDetail.as_view(),
        name='laporankasususer-detail'),
    path(
        'u/<uuid:pk>/',
        LaporanKasusUserUpdate.as_view(),
        name='laporankasususer-update'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        'q/<uuid:pk>/',
        LaporanKasusContinue,
        name='laporankasus-continue'),
    path(
        'p/',
        LaporanKasusSave,
        name='laporankasus-save'),
    path(
        'print/<pk>/',
        LaporanKasusPrint.as_view(),
        name='laporankasus-print'),   
]

LaporanKasusUser/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from .views import LaporanKasusUserCreate
from .views import LaporanKasusUserUpdate
from .views import LaporanKasusUserDetail
from .views import LaporanKasusUserStatus
from .views import LaporanKasusUserDelete
from .views import LaporanKasusUserConfirm


app_name = 'laporankasususer'

urlpatterns = [
    path(
        'c/',
        LaporanKasusUserCreate.as_view(),
        name='laporankasususer-create'),
    path(
        'u/<uuid:pk>/',
        LaporanKasusUserUpdate.as_view(),
        name='laporankasususer-update'),
    path(
        'd/<uuid:pk>/',
        LaporanKasusUserDetail.as_view(),
        name='laporankasususer-detail'),
    path(
        's/<uuid:pk>/',
        LaporanKasusUserStatus.as_view(),
        name='laporankasususer-status'),
    path(
        'x/<uuid:pk>/',
        LaporanKasusUserDelete.as_view(),
        name='laporankasususer-delete'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        'q/<uuid:pk>/',
        LaporanKasusUserConfirm,
        name='laporankasususer-confirm'),
]

LaporanPolisi/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from .views import Index
from .views import LaporanPolisiCreate
#from .views import LaporanKasusUserUpdate
#from .views import LaporanKasusUserDetail
#from .views import LaporanKasusUserStatus
#from .views import LaporanKasusUserDelete
#from .views import LaporanKasusUserConfirm


app_name = 'laporanpolisi'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path(
        'c/',
        LaporanPolisiCreate.as_view(),
        name='laporanpolisi-create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('', include('LandingPage.urls')),
    path('proadmin/', admin.site.urls),
    # path('lp/', include('LandingPage.urls')),
    path('feone/', include('LaporanKehilanganUser.urls')),
    path('fetwo/', include('LaporanKasusUser.urls')),
    path('beone/', include('LaporanKehilangan.urls')),
    path('betwo/', include('LaporanKasus.urls')),
    path('bethree/', include('LaporanPolisi.urls')),
    # path('tinymce/', include('tinymce.urls')),
    # path('laporankehilanganuser/', include('LaporanKehilanganUser.urls')),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),
    
    # rest api
    # path('theapi/', include('restapi.urls')),
]

InitData/models.py
from django.db import models


class KepalaSiaga(models.Model):
    jabatan = models.CharField(max_length=20)

    def __str__(self):
        return '%s' % (self.jabatan)


class Lokasi(models.Model):
    kode = models.CharField(max_length=20)
    deskripsi = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return '%s' % (self.kode)


class Kelamin(models.Model):
    jenis_kelamin = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.jenis_kelamin)


class Agama(models.Model):
    jenis_agama = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.jenis_agama)


class Pekerjaan(models.Model):
    jenis_pekerjaan = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.jenis_pekerjaan)


class Kebangsaan(models.Model):
    jenis_kebangsaan = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.jenis_kebangsaan)

class ModelLaporan(models.Model):
    model_laporan = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return '%s' % (self.model_laporan)

class Direktorat(models.Model):
    direktorat = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return '%s' % (self.direktorat)

LaporanPolisi/models.py
import hashlib
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from InitData.models import Kelamin, Agama, Pekerjaan, Kebangsaan, ModelLaporan, Direktorat
from core.models import UpperCaseCharField, UpperCaseCharWithoutSpaceField, UpperCaseEmailField

# from django.utils import timezone
# from tinymce import models as tinymce_models


class LaporanPolisi(models.Model):
    # Main Fields
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    nama = UpperCaseCharField(max_length=50)
    tempat_lahir = UpperCaseCharField(max_length=20, default=None)
    tanggal_lahir = models.DateField(
        auto_now=False, auto_now_add=False, default=None)
    kelamin = models.ForeignKey(
        Kelamin, default=1, on_delete=models.DO_NOTHING)
    agama = models.ForeignKey(Agama, default=1, on_delete=models.DO_NOTHING)
    pekerjaan = models.ForeignKey(
        Pekerjaan, default=1, on_delete=models.DO_NOTHING)
    kebangsaan = models.ForeignKey(
        Kebangsaan, default=1, on_delete=models.DO_NOTHING)
    # alamat = models.CharField(max_length=200)
    alamat = UpperCaseCharField(max_length=200)
    kota = UpperCaseCharField(max_length=20)
    nomor_telpon = UpperCaseCharField(max_length=20)
    email = UpperCaseEmailField(blank=True)

    # Kasus Field
    terlapor = UpperCaseCharField(max_length=50)
    korban = UpperCaseCharField(max_length=50)
    perkara = UpperCaseCharField(max_length=50)
    saksi = UpperCaseCharField(max_length=100)
    kerugian = UpperCaseCharField(max_length=200)
    waktu_kejadian = models.DateTimeField(
        auto_now=False, auto_now_add=False, default=None)
    tempat_kejadian = UpperCaseCharField(max_length=200)
    uraian_singkat_kejadian = models.TextField()

    # Nomor Surat
    nomor_surat = models.PositiveIntegerField(default=0)
    nomor_surat_text = UpperCaseCharField(max_length=50, blank=True)
    waktu_pelaporan = models.DateTimeField(auto_now=False, auto_now_add=True)
    lokasi_pelaporan = UpperCaseCharWithoutSpaceField(max_length=50)

    # Kasus
    # tindak_pidana = models.CharField(max_lenght=50)
    pasal_perkara = UpperCaseCharField(max_length=50)
    barang_bukti = models.TextField()

    # Some more field untuk Model - A
    tindakan_yang_diambil = models.CharField(
        max_length=100, default="Membuat Laporan Polisi")
    # peristiwa_dilaporkan = perkara if ModelLaporan = Model - B
    peristiwa_dilaporkan = models.CharField(max_length=100)

    # Model Laporan A/B/B1
    model_laporan = models.ForeignKey(
        ModelLaporan, default=1, on_delete=models.DO_NOTHING)
    
    # Direktorat
    direktorat = models.ForeignKey(
        Direktorat, default=1, on_delete=models.DO_NOTHING)

    # Tanda Tangan
    jabatan = UpperCaseCharField(max_length=20)
    pembuat_laporan = UpperCaseCharField(max_length=30, blank=True)
    pangkat_pembuat_laporan = UpperCaseCharField(max_length=50, blank=True)

    # Penerima Laporan
    nama_penerima_laporan = UpperCaseCharField(max_length=50)
    pangkat_penerima_laporan = UpperCaseCharField(max_length=50)

    # Additional Fields for control
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hash_field = models.PositiveIntegerField(default=0)
    is_valid = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)

    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, default=1)

    # keterangan_kehilangan = tinymce_models.HTMLField(blank=True)

    def __str__(self):
        return '%s' % (self.nomor_surat_text)


'''
    def get_absolute_url(self):
        return reverse(
            'laporankasus:laporankasus-detail', kwargs={'pk': self.pk})

'''

LaporanPolisi/views.py
from django.shortcuts import render
from django.conf import settings
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, TemplateView
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist
# from django.core.exceptions import EmptyResultSet
from django.http import Http404
from django.shortcuts import get_object_or_404
# from templated_email import send_templated_mail
from mail_templated import send_mail
from mail_templated import EmailMessage
from LaporanPolisi.forms import LaporanPolisiForm
from LaporanPolisi.models import LaporanPolisi


class Index(TemplateView):
    template_name = 'LaporanPolisi/index.html'

class LaporanPolisiCreate(CreateView):
    model = LaporanPolisi
    form_class = LaporanPolisiForm
    template_name = 'LaporanPolisi/add_form.html'
    # success_url = reverse_lazy('laporankasususer-detail')
    # fields = '__all__'

"""
class LaporanKasusUserUpdate(UpdateView):
    model = LaporanKasusUser
    form_class = LaporanKasusUserForm
    template_name = 'LaporanKasusUser/user_edit_form.html'
    # success_url = reverse_lazy('laporankasususer-detail')

    # This is to prevent direct call the link without referer
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER') or settings.DEBUG:
            # print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKasusUserUpdate,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")


class LaporanKasusUserDetail(DetailView):
    model = LaporanKasusUser
    # form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKasusUser/user_detail_form.html'

    # This is to prevent direct call the link without referer
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER') or settings.DEBUG:
            print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKasusUserDetail,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")

class LaporanKasusUserStatus(DetailView):
    model = LaporanKasusUser
    # form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKasusUser/user_status_form.html'


class LaporanKasusUserDelete(DeleteView):
    model = LaporanKasusUser
    success_url = reverse_lazy('landingpage-cancel')


# def QRCodeGenerator(request, pk, hf):
# def LaporanKehilanganUserConfirm(request, pk, hf):
def LaporanKasusUserConfirm(request, pk):
    if request.META.get('HTTP_REFERER') or settings.DEBUG:
        # print(request.META.get('HTTP_REFERER'))
        # qs = LaporanKehilanganUser.objects.filter(id=pk)
        # if qs.count() > 0:

        try:
            qs = LaporanKasusUser.objects.get(id=pk, is_valid=False)

            # send email here. Check if is_valid=True
            message = EmailMessage(
                'LaporanKasusUser/confirm.tpl', {
                    'DEBUG':
                    settings.DEBUG,
                    'object':
                    qs,
                    'request':
                    request,
                    'laporankehilanganuser_url':
                    request.build_absolute_uri(
                        reverse(
                            'laporankasususer:laporankasususer-status', kwargs={'pk': pk
                                                                    })),
                }, 'noreply@spkt.id', [qs.email])
            # do Something
            message.send()

            qs.is_valid = True
            qs.save()

        except ObjectDoesNotExist:
            raise Http404("Record is not found!")

        return render(request, 'LaporanKasusUser/user_confirm_form.html',
                      {
                          'pk': pk,
                          'hf': qs.hash_field,
                      })
        # else:
        #    raise Http404("Record is not found!")
    else:
        raise Http404("Record is not found!")


"""

LaporanPolisi/templates/LaporanPolisi/add_form.html
{% extends 'LaporanPolisi/base.html' %}
{% load static %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>Laporan Polisi</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
            <div class="row">
                    <div class="col-lg-3">
                            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                                    <div class="card-header">Kartu Informasi</div>
                                    <div class="card-body">
                                        <h4 class="card-title">Laporan Polisi</h4>
                                        <p class="card-text">Laporan Polisi</p>
                                    </div>
                            </div>
                    </div>
                

                    <div class="col-lg-9">
                        <div class="bs-component">
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="pernyataan" style="text-align: center">
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya">
            Klik kotak disamping untuk menyatakan data sudah benar.
        </label>
        <br>
        <br>
        <br>
        <p align="center">
        <button type="submit" class="btn btn-success btn-sm" :disabled="!checked">
            Kirim
        </button>
        </p>
    </div>
    </form>
                        </div>
                    </div>
                

            </div>
        </div>
    <!-- Code for vue.js -->
    <script src="{% static "LaporanKasusUser/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}

LaporanPolisi/templates/LaporanPolisi/base-status.html
{% load static %}
{% load l10n %}
{% load bootstrap3 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config.APPNAME }}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static "assets/css/jquery-ui.css" %}">
    <script src="{% static "assets/js/jquery-ui.js" %}"></script>
    <!--
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    -->
    <!-- For TinyMCE
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    {{ form.media }}
    -->
        <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    -->
</head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-md-1 bg-primary">
                    <img class="d-block mx-auto img-fluid" src="{% static "assets/images/lambang_polda_metro_jaya.png" %}">
                </div>
                <div class="col-md-11 bg-primary">
                    <h1 class="text-light text-center p-2">SENTRA PELAYANAN KEPOLISIAN TERPADU</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <br>
        <br>
        <br>
        <br>
        {% block content %}
        {% endblock %}

        {% include "LandingPage/footer.html" %}
    </div>
}
</body>
</html>

LaporanPolisi/templates/LaporanPolisi/continue_process.html
{% extends 'LaporanKasus/base.html' %}
{% load static %}
{% load qr_code %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>{% if object.is_approved %}
                        Approved
                        {% else %}
                        Draft
                        {% endif %}
                        Laporan Kasus</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
             <div class="row">
                <div class="col-lg-3">
                    <div class="card bg-light mb-3 mx-auto" style="max-width: 20rem;">
                        
                        <div class="card-header" style="text-align: center">
                        {% if object.is_valid %}
                            <span class="badge badge-success">Valid</span>
                        {% else %}
                            <span class="badge badge-danger">Invalid</span>
                        {% endif%}
                        {% if object.is_approved %}
                            <span class="badge badge-success">Approved</span>
                        {% else %}
                            <span class="badge badge-warning">Draft</span>
                        {% endif%}
                        QR Code<h1>{{ object.hash_field }}</h1></div>
                        <div class="card-body" style="padding: 0rem">
                        {% qr_from_text object.id size="M" %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">

                    <div class="card text-white bg-primary mb-3">
                        <div class="card-body">
                            <p>
                                Dengan ini saya:
                          </p>
                            <table>
                                <tr>
                                    <td>Nama</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.nama|upper }}</td>
                                </tr>
                                <!-- Tempat dan Tanggal Lahir -->
                                <tr>
                                    <td>Tempat tanggal lahir</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.tempat_lahir|upper }}, {{ object.tanggal_lahir|date:"d F Y"|upper }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Jenis kelamin</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.kelamin|upper }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>WargaNegara/Suku/Agama</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{% if object.kebangsaan|upper != "WNA" %} 
                                        INDONESIA {% else %} ASING {% endif %} 
                                        / 
                                        {{ object.agama|upper }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Pekerjaan</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.pekerjaan|upper }}
                                    </td>
                                </tr>
                                <!-- Alamat -->
                                <tr>
                                    <td>Alamat</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.alamat|upper }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        &nbsp;
                                    </td>
                                    <td>
                                        &nbsp;
                                    </td>
                                    <td>{{ object.kota|upper }}</td>
                                </tr>
                                <tr>
                                    <td>Telp/Fax/Email</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.nomor_telpon }} / {{ object.email|upper }}</td>
                                </tr>
                            </table>
        
                            <br>
        
                            <p>
                                    Peristiwa Yang Dilaporkan:
                            </p>
                            <table>
                                <tr>
                                    <td>1.</td>
                                    <td>Perkara</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.perkara|upper }}</td>
                                </tr>
                                <tr>
                                    <td>2.</td>
                                    <td>Waktu Kejadian</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.waktu_kejadian|date:"d F Y H:i"|upper }}</td>
                                </tr>
                                <tr>
                                    <td>3.</td>
                                    <td>Tempat Kejadian</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.tempat_kejadian|upper }}</td>
                                </tr>
                                <tr>
                                    <td>4.</td>
                                    <td>Terlapor</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.terlapor|upper }}</td>
                                </tr>
                                <tr>
                                    <td>5.</td>
                                    <td>Korban</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.korban|upper }}</td>
                                </tr>
                                <tr>
                                    <td>6.</td>
                                    <td>Saksi-saksi</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.saksi|upper }}</td>
                                </tr>
                                <tr>
                                    <td>7.</td>
                                    <td>Kerugian</td>
                                    <td>&nbsp;:&nbsp;</td>
                                    <td>{{ object.kerugian|upper }}</td>
                                </tr>        
                            </table>
        
        
                        </div>
                    </div> <!-- Card -->
<br>

<form action="{% url 'laporankasus:laporankasus-save' %}" method="post">
{% csrf_token %}
    <input type="hidden" name="id_id" value="{{ object.id }}">
    <input type="hidden" name="id_nama" value="{{ object.nama }}">
    <input type="hidden" name="id_nama" value="{{ object.nama }}">
    <input type="hidden" name="id_tempat_lahir" value="{{ object.tempat_lahir }}">
    <input type="hidden" name="id_tanggal_lahir" value="{{ object.tanggal_lahir }}">
    <input type="hidden" name="id_kelamin" value="{{ object.kelamin }}">
    <input type="hidden" name="id_agama" value="{{ object.agama }}">    
    <input type="hidden" name="id_pekerjaan" value="{{ object.pekerjaan }}">    
    <input type="hidden" name="id_kebangsaan" value="{{ object.kebangsaan }}">    
    <input type="hidden" name="id_alamat" value="{{ object.alamat }}">    
    <input type="hidden" name="id_kota" value="{{ object.kota }}">    
    <input type="hidden" name="id_nomor_telpon" value="{{ object.nomor_telpon }}">    
    <input type="hidden" name="id_email" value="{{ object.email }}">
    <!-- Specific Fields -->
    <input type="hidden" name="id_perkara" value="{{ object.perkara }}">    
    <input type="hidden" name="id_waktu_kejadian" value="{{ object.waktu_kejadian }}">    
    <input type="hidden" name="id_tempat_kejadian" value="{{ object.tempat_kejadian }}">    
    <input type="hidden" name="id_terlapor" value="{{ object.terlapor }}">
    <input type="hidden" name="id_korban" value="{{ object.korban }}">    
    <input type="hidden" name="id_saksi" value="{{ object.saksi }}">
    <input type="hidden" name="id_kerugian" value="{{ object.kerugian }}">
   
    <!-- entry -->
    <fieldset>
    <div class="form-group">
        <label for="id_pembuat_laporan">Kepala SPKT/Atas Nama</label>
        <input type="text" name="id_pembuat_laporan" class="form-control" placeholder="Kepala SPKT atau Atas Nama">
    </div>
    <div class="form-group">
        <label for="id_pangkat_pembuat_laporan">Pangkat Atas Nama</label>
        <input type="text" name="id_pangkat_pembuat_laporan" class="form-control" placeholder="Pangkat Atas Nama">
    </div>
    <div class="form-group">
        <label for="id_jabatan">Jabatan</label>
        <input type="text" name="id_jabatan" class="form-control" placeholder="KA. SIAGA I/II/III">
    </div>
    <div class="form-group">
        <label for="id_nama_penerima_laporan">Penerima/Pembuat Laporan</label>
        <input type="text" name="id_nama_penerima_laporan" class="form-control" placeholder="Penerima/Pembuat Laporan">
    </div>
    <div class="form-group">
        <label for="id_pangkat_penerima_laporan">Pangkat Penerima/Pembuat Laporan</label>
        <input type="text" name="id_pangkat_penerima_laporan" class="form-control" placeholder="Pangkat Penerima/Pembuat Laporan">
    </div>
    </fieldset>
    <div class="form-group">
        <label for="id_lokasi_pelaporan">Lokasi Pelaporan</label>
        <input type="text" name="id_lokasi_pelaporan" class="form-control" placeholder="SPKT/MPP/POLSEK/POLRES">
    </div>
    <div class="form-group">
        <label for="id_direktorat">Direktorat</label>
        <!--
            <input type="text" name="id_lokasi_pelaporan" class="form-control" placeholder="SPKT/MPP/POLSEK/POLRES">
        -->
        <select name="id_direktorat" class="form-control" placeholder="Dit. Reskrimum/Reskrimsus/Resnarkoba">
            {% for direktorat in direktorats %}
                <option value="{{ direktorat.id }}">{{ direktorat.deskripsi }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_pasal_perkara">Pasal Perkara</label>
        <input type="text" name="id_pasal_perkara" class="form-control" placeholder="Pasal berhubungan dengan Perkara">
    </div>
    <div class="form-group">
        <label for="id_barang_bukti">Barang Bukti</label>
        <textarea name="id_barang_bukti" id="id_barang_bukti" class="form-control" rows="8" placeholder="Daftar barang bukti"></textarea>
    </div>
    <div class="form-group">
        <label for="id_uraian_singkat_kejadian">Uraian Singkat Kejadian</label>
        <textarea name="id_uraian_singkat_kejadian" id="id_uraian_singkat_kejadian" class="form-control" rows="8" placeholder="Uraian kejadian silakan di uraikan disini"></textarea>
    </div>


<div id="pernyataan">
        <h3>Konfirmasi:</h3>
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya Jika Data sudah benar">
            <h6>Dengan ini saya memastikan informasi yang ada sudah benar adanya.</h6>
        </label>
        <br>
        <br>
        <br>

<button type="submit" class="btn btn-success" :disabled="!checked">Proses Lebih Lanjut</button></a>
<!--<a href="{% url 'laporankasus:laporankasususer-update' object.id %}"><button type="submit" class="btn btn-info">Sunting</button></a>-->
</form>
</div>
                    </div>
                </div>
            </div>
        </div>
    <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
-->
    <script src="{% static "assets/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}

LaporanPolisi/templates/LaporanPolisi/index.html
{% extends 'LaporanKehilangan/base.landing.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
        <div class="jumbotron">
            <img class="img-fluid d-block mx-auto" src="{% static "assets/images/lambang_polda_metro_jaya.png" %}" height="1">
            <h1 class="display-4">SENTRA PELAYANAN KEPOLISIAN TERPADU</h1>
            <hr class="my-4">
            <form method="post" action="{% url 'laporanpolisi:laporanpolisi-create' %}">
                    {% csrf_token %} 
                <fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Buat Laporan Polisi</button>
                    </div>
                </fieldset> 
            </form>    
        </div>
    </div>
    <div class="col-lg-2">

    </div>
</div>

{% endblock %}