LaporanKehilangan/urls.py
from django.urls import path
from LaporanKehilangan.views import Index, getLaporanKehilanganUserDetail
from LaporanKehilangan.views import LaporanKehilanganUserDetail, LaporanKehilanganUserUpdate
from LaporanKehilangan.views import LaporanKehilanganContinue, LaporanKehilanganSave
from LaporanKehilangan.views import LaporanKehilanganPrint

app_name = 'laporankehilangan'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path(
        'g/',
        getLaporanKehilanganUserDetail,
        name='getlaporankehilanganuser-detail'),
    path(
        'd/<uuid:pk>/',
        LaporanKehilanganUserDetail.as_view(),
        name='laporankehilanganuser-detail'),
    path(
        'u/<uuid:pk>/',
        LaporanKehilanganUserUpdate.as_view(),
        name='laporankehilanganuser-update'),
    #path(
    #    'e/<int:hf>/',
    #    LaporanKehilanganUserDetail.as_view(),
    #    name='laporankehilanganuser-detail-hf'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        'q/<uuid:pk>/',
        LaporanKehilanganContinue,
        name='laporankehilangan-continue'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        # 'p/<uuid:pk>/',
        'p/',
        LaporanKehilanganSave,
        name='laporankehilangan-save'),
    path(
        'print/<pk>/',
        LaporanKehilanganPrint.as_view(),
        name='laporankehilangan-print'),        
]

LaporanKehilanganUser/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from .views import LaporanKehilanganUserCreate
from .views import LaporanKehilanganUserUpdate
from .views import LaporanKehilanganUserDetail
from .views import LaporanKehilanganUserStatus
from .views import LaporanKehilanganUserDelete
from .views import LaporanKehilanganUserConfirm

app_name = 'laporankehilanganuser'

urlpatterns = [
    path(
        'c/',
        LaporanKehilanganUserCreate.as_view(),
        name='laporankehilanganuser-create'),
    path(
        'u/<uuid:pk>/',
        LaporanKehilanganUserUpdate.as_view(),
        name='laporankehilanganuser-update'),
    path(
        'd/<uuid:pk>/',
        LaporanKehilanganUserDetail.as_view(),
        name='laporankehilanganuser-detail'),
    path(
        's/<uuid:pk>/',
        LaporanKehilanganUserStatus.as_view(),
        name='laporankehilanganuser-status'),
    path(
        'x/<uuid:pk>/',
        LaporanKehilanganUserDelete.as_view(),
        name='laporankehilanganuser-delete'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        'q/<uuid:pk>/',
        LaporanKehilanganUserConfirm,
        name='laporankehilanganuser-confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('', include('LandingPage.urls')),
    path('proadmin/', admin.site.urls),
    # path('lp/', include('LandingPage.urls')),
    path('feone/', include('LaporanKehilanganUser.urls')),
    path('fetwo/', include('LaporanKasusUser.urls')),
    path('beone/', include('LaporanKehilangan.urls')),
    path('betwo/', include('LaporanKasus.urls')),
    path('bethree/', include('LaporanPolisi.urls')),
    # path('tinymce/', include('tinymce.urls')),
    # path('laporankehilanganuser/', include('LaporanKehilanganUser.urls')),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),
    
    # rest api
    # path('theapi/', include('restapi.urls')),
]

LaporanKehilangan/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from tinymce import models as tinymce_models
from InitData.models import KepalaSiaga
from InitData.models import Kelamin, Agama, Pekerjaan, Kebangsaan
from core.models import UpperCaseCharField, UpperCaseCharWithoutSpaceField, UpperCaseEmailField

# from core.templatetags.core_tags import nomorsuratLaporanKehilangan


class LaporanKehilangan(models.Model):
    # Main Fields
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    nama = UpperCaseCharField(max_length=50)
    tempat_lahir = UpperCaseCharField(max_length=20, default=None)
    tanggal_lahir = models.DateField(
        auto_now=False, auto_now_add=False, default=None)
    kelamin = models.ForeignKey(
        Kelamin, default=1, on_delete=models.DO_NOTHING)
    agama = models.ForeignKey(Agama, default=1, on_delete=models.DO_NOTHING)
    pekerjaan = models.ForeignKey(
        Pekerjaan, default=1, on_delete=models.DO_NOTHING)
    kebangsaan = models.ForeignKey(
        Kebangsaan, default=1, on_delete=models.DO_NOTHING)
    alamat = UpperCaseCharField(max_length=200)
    kota = UpperCaseCharField(max_length=20)
    nomor_telpon = UpperCaseCharField(max_length=20)
    email = UpperCaseEmailField(blank=True)
    jenis_barang_hilang = UpperCaseCharField(max_length=100)
    tanggal_kehilangan = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, default=timezone.now)
    lokasi_kehilangan = UpperCaseCharField(max_length=50, blank=True)
    keterangan_kehilangan = models.TextField(blank=True)
    # keterangan_kehilangan = tinymce_models.HTMLField(blank=True)

    # Some more fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hash_field = models.PositiveIntegerField(default=0)
    is_valid = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)

    # Nomor Surat
    nomor_surat = models.PositiveIntegerField(default=0)
    nomor_surat_text = UpperCaseCharField(max_length=50, blank=True)
    waktu_pelaporan = models.DateTimeField(auto_now=False, auto_now_add=True)
    lokasi_pelaporan = UpperCaseCharWithoutSpaceField(max_length=50)

    # Tanda Tangan
    pembuat_laporan = UpperCaseCharField(max_length=30, blank=True)
    # jabatan = models.ForeignKey(
    #    KepalaSiaga, default=1, on_delete=models.DO_NOTHING)
    jabatan = UpperCaseCharField(max_length=20)
    pangkat_pembuat_laporan = UpperCaseCharField(max_length=50, blank=True)

    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, default=1)

    def __str__(self):
        return '%s' % (self.nomor_surat_text)

    def get_absolute_url(self):
        return reverse('laporankehilangan-detail', kwargs={'pk': self.pk})


'''
    def save(self):
        self.full_clean()
        nomor_surat = nomorsuratLaporanKehilangan()
        nomor

        super(LaporanKehilangan, self).save(*args, **kwargs)
'''

LaporanKehilangan/views.py
from django.views.generic import DetailView, TemplateView, UpdateView
from django.conf import settings
from django.http import Http404
from django.utils import timezone
from django.shortcuts import render, redirect, reverse
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from LaporanKehilanganUser.models import LaporanKehilanganUser
from LaporanKehilanganUser.forms import LaporanKehilanganUserForm
from LaporanKehilangan.models import LaporanKehilangan
from LaporanKehilanganUser.views import LaporanKehilanganUserDetail
from LaporanKehilanganUser.views import  LaporanKehilanganUserUpdate
from InitData.models import Agama, Kelamin, Kebangsaan, Pekerjaan, Lokasi
from core.templatetags.core_tags import nomorsuratLaporanKehilangan
from core.templatetags.core_filters import roman_number


class Index(TemplateView):
    template_name = 'LaporanKehilangan/index.html'


def getLaporanKehilanganUserDetail(request):
    template_name = "LaporanKehilangan/user_status_form.html"
    if request.POST and request.POST['qrcode']:
        qrcode = request.POST['qrcode']
        # if isinstance(qrcode, int):
        if qrcode.isdigit():
            try:
                qs = LaporanKehilanganUser.objects.get(
                    hash_field=qrcode, is_valid=True, is_expired=False)
                STATUS = True
            except ObjectDoesNotExist:
                raise Http404("Record is not found!")

            if qs.is_approved:
                try:
                    qs = LaporanKehilangan.objects.get(
                        hash_field=qrcode, is_valid=True, is_expired=False
                    )
                    STATUS = False
                    print(qs.is_approved)
                except ObjectDoesNotExist:
                    raise Http404("Record is not found!")

        else:
            try:
                qs = LaporanKehilanganUser.objects.get(
                    id=qrcode, is_valid=True, is_expired=False)
                STATUS = True
            except ObjectDoesNotExist:
                raise Http404("Record is not found!")

            if qs.is_approved:
                try:
                    qs = LaporanKehilangan.objects.get(
                        uuid=qrcode, is_valid=True, is_expired=False
                    )
                    STATUS = False
                except ObjectDoesNotExist:
                    raise Http404("Record is not found!")

        if STATUS:
            # Check if the report is_approved = False
            # If is_approved = True, disable "Sunting" Button and change with Ready to Print
            return redirect('laporankehilangan:laporankehilanganuser-detail', pk = qs.id)
        else:
            return redirect(reverse('laporankehilangan:laporankehilangan-print', args = {qs.id}))

    else:
        raise Http404("Record is not found!")


# class LaporanKehilanganUserDetail(DetailView):
# inherit from LaporanKehilanganUser.views
class LaporanKehilanganUserDetail(LaporanKehilanganUserDetail):
    model = LaporanKehilanganUser
    # form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilangan/user_status_form.html'

    # This is to prevent direct call the link without referer
    '''
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER') or settings.DEBUG:
            print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKehilanganUserDetail,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")
    '''

# class LaporanKehilanganUserUpdate(UpdateView):
class LaporanKehilanganUserUpdate(LaporanKehilanganUserUpdate):
    model = LaporanKehilanganUser
    form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilangan/user_edit_form.html'
    # success_url = reverse('laporankehilangan:laporankehilanganuser-detail')
    
    # This is to prevent direct call the link without referer
    '''
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER'):
            # print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKehilanganUserUpdate,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")
    '''

    def get_success_url(self, *args, **kwargs):
        return reverse('laporankehilangan:laporankehilanganuser-detail', args = {self.object.id})


# EDIT THIS FOR FURTHER PROCESSING
def LaporanKehilanganContinue(request, pk):
    if request.META.get('HTTP_REFERER'):
        # print(request.META.get('HTTP_REFERER'))
        # qs = LaporanKehilanganUser.objects.filter(id=pk)
        # if qs.count() > 0:

        try:
            qs = LaporanKehilanganUser.objects.get(id=pk, is_valid=True)

            qs.is_valid = True
            qs.save()

        except ObjectDoesNotExist:
            raise Http404("Record is not found!")
        
        lokasi = Lokasi.objects.all()

        return render(request, 'LaporanKehilangan/continue_process.html',
                      {
                          'pk': pk,
                          'hf': qs.hash_field,
                          'object': qs,
                          'lokasi': lokasi,
                      })
        # else:
        #    raise Http404("Record is not found!")
    else:
        raise Http404("Record is not found!")


        # EDIT THIS FOR FURTHER PROCESSING
def LaporanKehilanganSave(request):
    if request.META.get('HTTP_REFERER') or settings.DEBUG:

        agama = request.POST.get('id_agama')
        kelamin = request.POST.get('id_kelamin')
        pekerjaan = request.POST.get('id_pekerjaan')
        kebangsaan = request.POST.get('id_kebangsaan')
               
        qs = LaporanKehilangan()

        # Fields Foreignkey
        qs.agama = Agama.objects.get(jenis_agama=agama)
        qs.kelamin = Kelamin.objects.get(jenis_kelamin=kelamin)
        qs.pekerjaan = Pekerjaan.objects.get(jenis_pekerjaan=pekerjaan)
        qs.kebangsaan = Kebangsaan.objects.get(jenis_kebangsaan=kebangsaan)

        # Fields User
        qs.nama = request.POST.get('id_nama')
        qs.tempat_lahir = request.POST.get('id_tempat_lahir')
        qs.tanggal_lahir = request.POST.get('id_tanggal_lahir')
        qs.alamat = request.POST.get('id_alamat')
        qs.kota = request.POST.get('id_kota')
        qs.nomor_telpon = request.POST.get('id_nomor_telpon')
        qs.email = request.POST.get('id_email')
        qs.keterangan_kehilangan = request.POST.get('id_keterangan_kehilangan')
        qs.lokasi_kehilangan = request.POST.get('id_lokasi_kehilangan')
        qs.jenis_barang_hilang = request.POST.get('id_jenis_barang_hilang')
        qs.tanggal_kehilangan = request.POST.get('id_tanggal_kehilangan')
        
        # Field Back Office
        qs.jabatan = request.POST.get('id_jabatan')
        qs.pembuat_laporan = request.POST.get('id_pembuat_laporan')
        qs.pangkat_pembuat_laporan = request.POST.get('id_pangkat_pembuat_laporan')
        qs.lokasi_pelaporan = request.POST.get('id_lokasi_pelaporan')
        
        # Fields Control
        qs.uuid = request.POST.get('id_uuid')
        qs.hash_field = request.POST.get('id_hash_field')
        qs.is_valid = True
        qs.is_approved = True

        # Nomor Surat
        qs.nomor_surat = nomorsuratLaporanKehilangan()
        qs.nomor_surat_text = '%s / %s / %s / %s / %s / %s' % (
            qs.nomor_surat,
            'B',
            roman_number(timezone.now().month),
            timezone.now().year,
            qs.lokasi_pelaporan,
            'SPKT'
            )
            
        # qs.save()

        # Save into LaporanKehilangan    
        try:
            qs.save()
        except Exception:
            # from django.db import connection
            # print(connection.queries[-1])
            # print ('%s (%s)' % (e.message, type(e)))
            raise Http404("Something Wrong! Can't Save LK!")
        
        # Update LaporanKehilanganUser. is_approved=True
        id_uuid = request.POST.get('id_uuid')
        
        try:
            qs_user = LaporanKehilanganUser.objects.get(id=id_uuid)
        except ObjectDoesNotExist:
            raise Http404("Record is not found!")

        qs_user.is_approved = True;
        qs_user.is_valid = True;

        # Try to save into LaporanKehilanganUser
        try:
            qs_user.save()
        except Exception:
            raise Http404("Something Wrong! Can't Save!")

        # Get The Lastest record and 
        # try:
        #    qs = LaporanKehilangan.objects.get(uuid=id_uuid, is_valid=True, is_approved=True)

        # except ObjectDoesNotExist:
        #    raise Http404("Record is not found!")

        # return LaporanKehilanganPrint.as_view()(request, pk=qs.id)
        return redirect(reverse('laporankehilangan:laporankehilangan-print', args = {qs.id}))

    else:
        raise Http404("Record is not found!")


class LaporanKehilanganPrint(DetailView):
    model = LaporanKehilangan
    template_name = 'LaporanKehilangan/save_and_print.html'

    def get(self, request, *args, **kwargs):
        print(self.request.META.get('HTTP_REFERER'))
        print(settings.DEBUG)
        if self.request.META.get('HTTP_REFERER') or settings.DEBUG:
            self.object = self.get_object()
            context = super(LaporanKehilanganPrint,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")

LaporanKehilangan/templates/LaporanKehilangan/user_detail_form.html
{% extends 'LaporanKehilangan/base.html' %}
{% load static %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>Draft Laporan Kehilangan</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
            <div class="row">
                <div class="col-lg-3">
                    <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                        <div class="card-header">Kartu Informasi</div>
                        <div class="card-body">
                    <h4 class="card-title">Draft Surat Kehilangan</h4>
                    <p class="card-text">Informasi ini akan menjadi data masukkan bagi SPKT terdekat untuk mengeluarkan Surat Kehilangan.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">

<div class="card text-white bg-primary mb-3">
<div class="card-body">
<p>
    Dengan ini, saya seorang
        {% if object.kelamin|upper != "PEREMPUAN" %}
        Laki-Laki
        {% else %}
        Perempuan
        {% endif %}
     Bangsa
        {% if object.kebangsaan|upper != "WNA" %}
        Indonesia
        {% else %}
        Asing
        {% endif %}
        yang mengaku bernama:
</p>
<table>
    <tr>
        <td>Nama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nama|upper }}</td>
    </tr>
    <!-- Tempat dan Tanggal Lahir -->
    <tr>
        <td>Tempat tanggal lahir</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.tempat_lahir|upper }},
            {{ object.tanggal_lahir|date:"d F Y"|upper }}
        </td>
    </tr>
    <!-- Nomor Telpon -->
    <tr>
        <td>Nomor Telpon</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nomor_telpon }}</td>
    </tr>
    <!-- Email -->
    <tr>
        <td>Alamat Email</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.email|upper }}</td>
    </tr>
    <!-- Agama -->
    <tr>
        <td>Agama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.agama|upper }}</td>
    </tr>
    <!-- Pekerjaan -->
    <tr>
        <td>Pekerjaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.pekerjaan|upper }}</td>
    </tr>
    <!-- Kebangsaan -->
    <tr>
        <td>Kebangsaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>
            {% if object.kebangsaan != "WNA" %}
                INDONESIA
            {% else %}
                ASING
            {% endif %}

        </td>
    </tr>
    <!-- Alamat -->
    <tr>
        <td>Alamat</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.alamat|upper }}</td>
    </tr>
    <tr>
        <td>
            &nbsp;
        </td>
        <td>
            &nbsp;
        </td>
        <td>{{ object.kota|upper }}</td>
    </tr>
</table>

<br>

<p>
Melaporkan telah kehilangan surat / barang berupa:
</p>

<p style="white-space: pre-line">
Sebuah {{ object.jenis_barang_hilang|upper }}
{% if object.keterangan_kehilangan.strip %}
        {{ object.keterangan_kehilangan|safe }}
{% endif %}
</p>

<p>
Terjadi pada tanggal {{ object.tanggal_kehilangan|date:"d F Y" }} di {{ object.lokasi_kehilangan }}. Kerugian atas nama
    dan alamat tersebut di atas.
</p>

</div>
</div> <!-- Card -->

<br>
    <div id="pernyataan">
        <legend>Pernyataan:</legend>
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya">
            Dengan ini saya memastikan informasi yang saya berikan benar adanya.
        </label>
        <br>
        <br>
        <br>

<a href="{% url 'laporankehilangan:laporankehilanganuser-confirm' object.id %}"><button type="submit" class="btn btn-success btn-sm" :disabled="!checked">Kirim</button></a>
<a href="{% url 'laporankehilangan:laporankehilanganuser-update' object.id %}"><button type="submit" class="btn btn-info btn-sm">Sunting</button></a>
<a href="{% url 'laporankehilangan:laporankehilanganuser-delete' object.id %}"><button type="submit" class="btn btn-danger btn-sm">Batal</button></a>
   </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
-->
    <script src="{% static "LaporanKehilanganUser/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}

LaporanKehilangan/templates/LaporanKehilangan/user_status_form.html
{% extends 'LaporanKehilangan/base.html' %}
{% load static %}
{% load qr_code %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>{% if object.is_approved %}
                        Approved
                        {% else %}
                        Draft
                        {% endif %}
                        Laporan Kehilangan</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
            <!--
                <h3 class="text-white" contenteditable="true">Dear, {{ object.nama|upper }}</h3>
                <p class="lead">Anda telah berhasil membuat Laporan Kehilangan Anda pada {{ object.created_at|date:"d F Y H:m T" }}. 
                    Berikut adalah tiket laporan anda. Silahkan anda menuju kantor SPKT terdekat dan menunjukan e-tiket ini agar laporan anda dapat ditindaklanjuti. </p>
                -->
                <div class="row">
                <div class="col-lg-3">
                    <div class="card bg-light mb-3 mx-auto" style="max-width: 20rem;">
                        
                        <div class="card-header" style="text-align: center">
                        {% if object.is_valid %}
                            <span class="badge badge-success">Valid</span>
                        {% else %}
                            <span class="badge badge-danger">Invalid</span>
                        {% endif%}
                        {% if object.is_approved %}
                            <span class="badge badge-success">Approved</span>
                        {% else %}
                            <span class="badge badge-warning">Draft</span>
                        {% endif%}
                        QR Code<h1>{{ object.hash_field }}</h1></div>
                        <div class="card-body" style="padding: 0rem">
                        {% qr_from_text object.id size="M" %}
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">

<div class="card text-white bg-primary mb-3">
<div class="card-body">
</p>
Dengan ini, saya seorang
        {% if object.kelamin|upper != "PEREMPUAN" %}
        Laki-Laki
        {% else %}
        Perempuan
        {% endif %}
     Bangsa
        {% if object.kebangsaan|upper != "WNA" %}
        Indonesia
        {% else %}
        Asing
        {% endif %}
        yang mengaku bernama:
</p>
<table>
    <tr>
        <td>Nama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nama|upper }}</td>
    </tr>
    <!-- Tempat dan Tanggal Lahir -->
    <tr>
        <td>Tempat tanggal lahir</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.tempat_lahir|upper }},
            {{ object.tanggal_lahir|date:"d F Y"|upper }}
        </td>
    </tr>
    <!-- Nomor Telpon -->
    <tr>
        <td>Nomor Telpon</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nomor_telpon }}</td>
    </tr>
    <!-- Email -->
    <tr>
        <td>Alamat Email</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.email|upper }}</td>
    </tr>
    <!-- Agama -->
    <tr>
        <td>Agama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.agama|upper }}</td>
    </tr>
    <!-- Pekerjaan -->
    <tr>
        <td>Pekerjaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.pekerjaan|upper }}</td>
    </tr>
    <!-- Kebangsaan -->
    <tr>
        <td>Kebangsaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>
            {% if object.kebangsaan != "WNA" %}
                INDONESIA
            {% else %}
                ASING
            {% endif %}

        </td>
    </tr>
    <!-- Alamat -->
    <tr>
        <td>Alamat</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.alamat|upper }}</td>
    </tr>
    <tr>
        <td>
            &nbsp;
        </td>
        <td>
            &nbsp;
        </td>
        <td>{{ object.kota|upper }}</td>
    </tr>
</table>

<br>

<p>
Melaporkan telah kehilangan surat / barang berupa:
</p>

<p style="white-space: pre-line">
{{ object.jenis_barang_hilang|upper }}
{% if object.keterangan_kehilangan.strip %}
        {{ object.keterangan_kehilangan|safe }}
{% endif %}
</p>

<p>
Terjadi pada tanggal {{ object.tanggal_kehilangan|date:"d F Y" }} di {{ object.lokasi_kehilangan }}. Kerugian atas nama
    dan alamat tersebut di atas.
</p>

</div>
</div> <!-- Card -->

<br>
{% if not object.is_approved %}
<div id="pernyataan">
        <h3>Konfirmasi:</h3>
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya Jika Data sudah benar">
            <h6>Dengan ini saya memastikan informasi yang ada sudah benar adanya.</h6>
        </label>
        <br>
        <br>
        <br>

<a href="{% url 'laporankehilangan:laporankehilangan-continue' object.id %}"><button type="submit" class="btn btn-success" :disabled="!checked">Proses Lebih Lanjut</button></a>
<a href="{% url 'laporankehilangan:laporankehilanganuser-update' object.id %}"><button type="submit" class="btn btn-info">Sunting</button></a>
</div>
{% else %}
<div>
<a href="{% url 'laporankehilangan:laporankehilangan-print' object.id %}"><button type="submit" class="btn btn-info">Laporan sudah di approve. Siap di cetak.</button></a>
</div>

{% endif %}

                    </div>
                </div>
            </div>
        </div>
    <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
-->
    <script src="{% static "LaporanKehilanganUser/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}