LandingPage/urls.py
from django.urls import path
from .views import Index, Cancel


app_name = 'landingpage'

urlpatterns = [
    path(
        '',
        Index.as_view(),
        name='landingpage-index'),
    path(
        'batal/',
        Cancel.as_view(),
        name='landingpage-cancel'),
]

LaporanKehilanganUser/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from .views import LaporanKehilanganUserCreate
from .views import LaporanKehilanganUserUpdate
from .views import LaporanKehilanganUserDetail
from .views import LaporanKehilanganUserStatus
from .views import LaporanKehilanganUserDelete
from .views import LaporanKehilanganUserConfirm

app_name = 'laporankehilanganuser'

urlpatterns = [
    path(
        'c/',
        LaporanKehilanganUserCreate.as_view(),
        name='laporankehilanganuser-create'),
    path(
        'u/<uuid:pk>/',
        LaporanKehilanganUserUpdate.as_view(),
        name='laporankehilanganuser-update'),
    path(
        'd/<uuid:pk>/',
        LaporanKehilanganUserDetail.as_view(),
        name='laporankehilanganuser-detail'),
    path(
        's/<uuid:pk>/',
        LaporanKehilanganUserStatus.as_view(),
        name='laporankehilanganuser-status'),
    path(
        'x/<uuid:pk>/',
        LaporanKehilanganUserDelete.as_view(),
        name='laporankehilanganuser-delete'),
    path(
        # 'q/<uuid:pk>/<int:hf>/',
        'q/<uuid:pk>/',
        LaporanKehilanganUserConfirm,
        name='laporankehilanganuser-confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from qr_code import urls as qr_code_urls

urlpatterns = [
    path('', include('LandingPage.urls')),
    path('proadmin/', admin.site.urls),
    # path('lp/', include('LandingPage.urls')),
    path('feone/', include('LaporanKehilanganUser.urls')),
    path('fetwo/', include('LaporanKasusUser.urls')),
    path('beone/', include('LaporanKehilangan.urls')),
    path('betwo/', include('LaporanKasus.urls')),
    path('bethree/', include('LaporanPolisi.urls')),
    # path('tinymce/', include('tinymce.urls')),
    # path('laporankehilanganuser/', include('LaporanKehilanganUser.urls')),
    path('qr_code/', include(qr_code_urls, namespace="qr_code")),
    
    # rest api
    # path('theapi/', include('restapi.urls')),
]

LaporanKehilanganUser/models.py
import hashlib
import uuid
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from InitData.models import Kelamin, Agama, Pekerjaan, Kebangsaan
from core.models import UpperCaseCharField, UpperCaseEmailField

# from django.utils import timezone
# from tinymce import models as tinymce_models


class LaporanKehilanganUser(models.Model):
    # Main Fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nama = UpperCaseCharField(max_length=50)
    tempat_lahir = UpperCaseCharField(max_length=20, default=None)
    tanggal_lahir = models.DateField(
        auto_now=False, auto_now_add=False, default=None)
    kelamin = models.ForeignKey(
        Kelamin, default=1, on_delete=models.DO_NOTHING)
    agama = models.ForeignKey(Agama, default=1, on_delete=models.DO_NOTHING)
    pekerjaan = models.ForeignKey(
        Pekerjaan, default=1, on_delete=models.DO_NOTHING)
    kebangsaan = models.ForeignKey(
        Kebangsaan, default=1, on_delete=models.DO_NOTHING)
    alamat = UpperCaseCharField(max_length=200)
    kota = UpperCaseCharField(max_length=20)
    nomor_telpon = UpperCaseCharField(max_length=20)
    email = UpperCaseEmailField(blank=True)
    jenis_barang_hilang = UpperCaseCharField(max_length=100)
    tanggal_kehilangan = models.DateField(
        auto_now=False, auto_now_add=False, default=None)
    lokasi_kehilangan = UpperCaseCharField(max_length=50, blank=True)
    keterangan_kehilangan = models.TextField(blank=True)
    
    # Additional Fields for control
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    hash_field = models.PositiveIntegerField(default=0)
    is_valid = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    is_expired = models.BooleanField(default=False)

    # keterangan_kehilangan = tinymce_models.HTMLField(blank=True)

    def __str__(self):
        return '%s' % (self.id)

    def get_absolute_url(self):
        return reverse('laporankehilanganuser:laporankehilanganuser-detail', kwargs={'pk': self.pk})

    # def clean(self, *args, **kwargs):
    def clean(self):
        # Create hash string
        hash_string = "%s%s%s%s%s%s%s%s" % (
            slugify(self.nama),
            slugify(self.tempat_lahir),
            slugify(str(self.tanggal_lahir)),
            slugify(self.nomor_telpon),
            slugify(self.email),
            slugify(self.jenis_barang_hilang),
            slugify(str(self.tanggal_kehilangan)),
            slugify(self.lokasi_kehilangan),
        )

        # Encode the hash string to number
        hash_field = int(
            hashlib.sha256(hash_string.encode('utf-8')).hexdigest(),
            16) % 10**9

        # Do some validation
        query_string = LaporanKehilanganUser.objects.filter(
            hash_field=hash_field, is_valid=True)
        # query_string = self.objects.filter(
        #    hash_field=hash_field, is_valid=True)

        if self.id:
            query_string = query_string.exclude(pk=self.id)

        if query_string.count() > 0:
            raise ValidationError({
                'nama':
                'Laporan yang mirip sudah ada di sistem kami. \
                Apakah Anda membuat pelaporan yang sama?'
            })

        return self.id

    def save(self, *args, **kwargs):
        self.full_clean()

        # Create hash string
        hash_string = "%s%s%s%s%s%s%s%s" % (
            slugify(self.nama),
            slugify(self.tempat_lahir),
            slugify(str(self.tanggal_lahir)),
            slugify(self.nomor_telpon),
            slugify(self.email),
            slugify(self.jenis_barang_hilang),
            slugify(str(self.tanggal_kehilangan)),
            slugify(self.lokasi_kehilangan),
        )

        # Encode the hash string to number 9 Digit number
        self.hash_field = int(
            hashlib.sha256(hash_string.encode('utf-8')).hexdigest(),
            16) % 10**9

        super(LaporanKehilanganUser, self).save(*args, **kwargs)

LaporanKehilanganUser/forms.py
from django import forms
from django.forms import widgets
from LaporanKehilanganUser.models import LaporanKehilanganUser

# from django.forms.extras.widgets import SelectDateWidget
# from tinymce.widgets import TinyMCE
# from django.utils.translation import gettext_lazy as _


class LaporanKehilanganUserForm(forms.ModelForm):
    class Meta:
        model = LaporanKehilanganUser
        localized_fiels = '__all__'
        fields = [
            'nama',
            'tempat_lahir',
            'tanggal_lahir',
            'alamat',
            'kota',
            'kelamin',
            'agama',
            'pekerjaan',
            'kebangsaan',
            'nomor_telpon',
            'email',
            'jenis_barang_hilang',
            'tanggal_kehilangan',
            'lokasi_kehilangan',
            'keterangan_kehilangan',
        ]

        widgets = {
            # 'tanggal_lahir': SelectDateWidget(year=range(210, 1920, -1)),
            'nama':
            widgets.TextInput(attrs={
                'placeholder': 'Ketik Nama Lengkap',
                'class': 'form-control'
            }),
            'tempat_lahir':
            widgets.TextInput(attrs={
                'placeholder': 'Kota Tempat Anda Lahir',
                'class': 'form-control'
            }),
            'tanggal_lahir':
            forms.DateInput(
                format='%d-%m-%Y',
                attrs={
                    'class': 'datepicker form-control',
                    'placeholder': 'dd-mm-yyyy',
                    # widgets.DateInput(attrs={
                    #    'type': 'date',
                    #    'class': 'form-control',
                }),
            'tanggal_kehilangan':
            forms.DateInput(
                format='%d-%m-%Y',
                attrs={
                    'class': 'datepicker form-control',
                    'placeholder': 'dd-mm-yyyy',
                    # widgets.DateInput(attrs={
                    #    'type': 'date',
                    #    'class': 'form-control',
                }),
            'alamat':
            widgets.TextInput(attrs={
                'placeholder': 'Alamat tinggal Anda',
                'class': 'form-control',
            }),
            'kota':
            widgets.TextInput(attrs={
                'placeholder': 'Kota',
                'class': 'form-control',
            }),
            'nomor_telpon':
            widgets.TextInput(
                attrs={
                    'placeholder': 'Nomor Seluler Anda. Contoh: 08119998888',
                    'class': 'form-control',
                }),
            'jenis_barang_hilang':
            widgets.TextInput(
                attrs={
                    'placeholder': 'Contoh: STNK / SIM / MOBIL / ISTRI',
                    'class': 'form-control',
                }),
            'lokasi_kehilangan':
            widgets.TextInput(
                attrs={
                    'placeholder': 'Contoh: KANTOR / Sekitar Jalan Sudirman',
                    'class': 'form-control',
                }),
            'email':
            widgets.EmailInput(
                attrs={
                    'placeholder': 'Pastikan email Anda benar dan masih aktif',
                    'class': 'form-control',
                }),
            'kelamin':
            widgets.Select(attrs={
                'class': 'custom-select',
            }),
            'agama':
            widgets.Select(attrs={
                'class': 'custom-select',
            }),
            'pekerjaan':
            widgets.Select(attrs={
                'class': 'custom-select',
            }),
            'kebangsaan':
            widgets.Select(attrs={
                'class': 'custom-select',
            }),
            # 'tanggal_kehilangan': SelectDateWidget(),
            'keterangan_kehilangan':
            widgets.Textarea(
                attrs={
                    'class':
                    'form-control',
                    'placeholder':
                    'Tambahan keterangan mengenai barang yang hilang (jika ada).',
                }),
            # TinyMCE(attrs={
            #    'cols': 200,
            #    'rows': 80,
        }

        # help_texts = {
        # 'email': _('Pastikan email Anda benar dan masih aktif.'),
        # 'jenis_barang_hilang': _('Contoh: STNK, SIM, MOBIL.'),
        # 'keterangan_kehilangan':
        # _('Jabarkan detail kehilangan di kotak ini.'),
        # 'lokasi_kehilangan': _('Contoh: KANTOR, Sekitar Jalan Sudirman.'),
        # }

        # error_messages = {
        #    'email': _('Masukkan alamat email yang benar.'),
        # }

LaporanKehilanganUser/views.py
from django.shortcuts import render
from django.conf import settings
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist
# from django.core.exceptions import EmptyResultSet
from django.http import Http404
from django.shortcuts import get_object_or_404
# from templated_email import send_templated_mail
from mail_templated import send_mail
from mail_templated import EmailMessage
from LaporanKehilanganUser.forms import LaporanKehilanganUserForm
from LaporanKehilanganUser.models import LaporanKehilanganUser


class LaporanKehilanganUserCreate(CreateView):
    model = LaporanKehilanganUser
    form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilanganUser/user_add_form.html'
    # success_url = reverse_lazy('laporankehilanganuser-detail')


class LaporanKehilanganUserUpdate(UpdateView):
    model = LaporanKehilanganUser
    form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilanganUser/user_edit_form.html'
    # success_url = reverse_lazy('laporankehilanganuser-detail')

    # This is to prevent direct call the link without referer
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER'):
            # print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKehilanganUserUpdate,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")


class LaporanKehilanganUserDetail(DetailView):
    model = LaporanKehilanganUser
    # form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilanganUser/user_detail_form.html'

    # This is to prevent direct call the link without referer
    def get(self, request, *args, **kwargs):
        if self.request.META.get('HTTP_REFERER') or settings.DEBUG:
            print(self.request.META.get('HTTP_REFERER'))
            self.object = self.get_object()
            context = super(LaporanKehilanganUserDetail,
                            self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        else:
            raise Http404("Record is not found!")


class LaporanKehilanganUserStatus(DetailView):
    model = LaporanKehilanganUser
    # form_class = LaporanKehilanganUserForm
    template_name = 'LaporanKehilanganUser/user_status_form.html'


class LaporanKehilanganUserDelete(DeleteView):
    model = LaporanKehilanganUser
    success_url = reverse_lazy('landingpage:landingpage-cancel')


# def QRCodeGenerator(request, pk, hf):
# def LaporanKehilanganUserConfirm(request, pk, hf):
def LaporanKehilanganUserConfirm(request, pk):
    if request.META.get('HTTP_REFERER') or settings.DEBUG:
        # print(request.META.get('HTTP_REFERER'))
        # qs = LaporanKehilanganUser.objects.filter(id=pk)
        # if qs.count() > 0:

        try:
            qs = LaporanKehilanganUser.objects.get(id=pk, is_valid=False)

            # send email here. Check if is_valid=True
            message = EmailMessage(
                'LaporanKehilanganUser/confirm.tpl', {
                    'DEBUG':
                    settings.DEBUG,
                    'object':
                    qs,
                    'request':
                    request,
                    'laporankehilanganuser_url':
                    request.build_absolute_uri(
                        reverse(
                            'laporankehilanganuser:laporankehilanganuser-status', kwargs={'pk': pk
                                                                    })),
                }, 'noreply@spkt.id', [qs.email])
            # do Something
            message.send()

            qs.is_valid = True
            qs.save()

        except ObjectDoesNotExist:
            raise Http404("Record is not found!")

        return render(request, 'LaporanKehilanganUser/user_confirm_form.html',
                      {
                          'pk': pk,
                          'hf': qs.hash_field,
                      })
        # else:
        #    raise Http404("Record is not found!")
    else:
        raise Http404("Record is not found!")

LaporanKehilanganUser/templates/LaporanKehilanganUser/base-status.html
{% load static %}
{% load l10n %}
{% load bootstrap3 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config.APPNAME }}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    <!-- For TinyMCE
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    {{ form.media }}
    -->
        <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    -->
</head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        <div class="container">
            <div class="row">
                <div class="col-md-1 bg-primary">
                    <img class="d-block mx-auto img-fluid" src="{% static "assets/images/lambang_polda_metro_jaya.png" %}">
                </div>
                <div class="col-md-11 bg-primary">
                    <h1 class="text-light text-center p-2">SENTRA PELAYANAN KEPOLISIAN TERPADU</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <br>
        <br>
        <br>
        <br>
        {% block content %}
        {% endblock %}

        {% include "LandingPage/footer.html" %}
    </div>
}
</body>
</html>

LaporanKehilanganUser/templates/LaporanKehilanganUser/base.1.html
{% load static %}
{% load l10n %}
{% load bootstrap3 %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ config.APPNAME }}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    <!-- For TinyMCE
    <script type="text/javascript" src="{% static "tiny_mce/tiny_mce.js" %}"></script>
    {{ form.media }}
    -->
        <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
    -->
</head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
        <div class="container">
            <a href="/" class="navbar-brand">SPKT</a>
            <span class="badge badge-info">alpha</span>
        </div>
    </div>

    <div class="container">
        <br>
        <br>
        <br>
        {% block content %}
        {% endblock %}

        {% include "LandingPage/footer.html" %}
    </div>
}
</body>
</html>

LaporanKehilanganUser/templates/LaporanKehilanganUser/laporankehilanganuser_confirm_delete.html
{% extends 'LandingPage/base.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-dismissible alert-warning">
        <!--
            <button type="button" class="close" data-dismiss="alert">&times;</button>
        -->
        <h4 class="alert-heading">Konfirmasi</h4>
        <form action="" method="post">{% csrf_token %}
        <h1>Anda yakin ingin membatalkan Laporan?</h1>
        <button type="submit" class="btn btn-danger btn-lg">Batal</button>
        <button onclick="window.history.back();" type="button" class="btn btn-success btn-lg">Tidak</button>

        </form>
        </div>
    </div>
</div>

{% endblock %}

LaporanKehilanganUser/templates/LaporanKehilanganUser/user_add_form.html
{% extends 'LaporanKehilanganUser/base.html' %}
{% load static %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>Laporan Kehilangan</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
            <div class="row">
                    <div class="col-lg-3">
                            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                                    <div class="card-header">Kartu Informasi</div>
                                    <div class="card-body">
                                        <h4 class="card-title">Surat Kehilangan</h4>
                                        <p class="card-text">Surat Kehilangan bisa digunakan untuk mengurus barang hilang seperti KTP/SIM/STNK. Atau hal-hal lainnya. Istri hilang juga bisa diurus dengan Surat Kehilangan, sehingga Anda bisa kawin lagi. Asik khan.
                                            Pastikan data-data yang masukan benar adanya.</p>
                                    </div>
                            </div>
                    </div>
                

                    <div class="col-lg-9">
                        <div class="bs-component">
    <form action="{% url "laporankehilanganuser:laporankehilanganuser-create" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="pernyataan" style="text-align: center">
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya">
            Klik kotak disamping untuk menyatakan data sudah benar.
        </label>
        <br>
        <br>
        <br>
        <p align="center">
        <button type="submit" class="btn btn-success btn-sm" :disabled="!checked">
            Kirim
        </button>
        </p>
    </div>
    </form>
                        </div>
                    </div>
                

            </div>
        </div>
    <!-- Code for vue.js -->
    <script src="{% static "LaporanKehilanganUser/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}

LaporanKehilanganUser/templates/LaporanKehilanganUser/user_confirm_form.html
{% extends 'LaporanKehilanganUser/base.html' %} {% load qr_code %} {% block content %}
<div class="page-header">
    <div class="row" style="text-align: center;">
        <div class="col-lg-12">
            <h1>QR Code</h1>
        </div>
    </div>
</div>
<br>
<div class="bs-docs-section">
    <div class="row">
        <div class="col-lg-3">
            <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                <div class="card-header">Kartu Informasi</div>
                <div class="card-body">
                    <h4 class="card-title">QR Code</h4>
                    <p class="card-text">
                        Ini adalah QR Code. Informasi lebih lanjut sudah di email ke alamat email Anda. Cek email Anda and bawa QR Code ini ke Kantor
                        Polisi untuk memproses laporan Anda lebih lanjut.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-6" style="text-align: center">

            <div class="card bg-light mb-3 mx-auto" style="max-width: 20rem;">
                <div class="card-body">
                    {% qr_from_text pk size="M" %}
                </div>
            </div>
            <h1>{{ hf }}</h1>
            <!--
                        <h5>{{ pk }}</h5>
                        -->
            <a href="{% url 'landingpage:landingpage-index' %}">
                <button class="btn btn-primary btn-lg">Kembali Ke Halaman Awal</button>
            </a>
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>
</div>
<script>
    /* break back button */
    window.onload = function () {
        var i = 0;
        var previous_hash = window.location.hash;
        var x = setInterval(function () {
            i++;
            window.location.hash = "/noop/" + i;
            if (i == 99) {
                clearInterval(x);
                window.location.hash = previous_hash;
            }
        }, 10);
    }
</script>
{% endblock %}

LaporanKehilanganUser/templates/LaporanKehilanganUser/user_detail_form.html
{% extends 'LaporanKehilanganUser/base.html' %}
{% load static %}
{% block content %}
        <div class="page-header">
            <div class="row" style="text-align: center;">
                <div class="col-lg-12">
                    <h1>Draft Laporan Kehilangan</h1>
                </div>
            </div>
        </div>
        <br>
        <div class="bs-docs-section">
            <div class="row">
                <div class="col-lg-3">
                    <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                        <div class="card-header">Kartu Informasi</div>
                        <div class="card-body">
                    <h4 class="card-title">Draft Surat Kehilangan</h4>
                    <p class="card-text">Informasi ini akan menjadi data masukkan bagi SPKT terdekat untuk mengeluarkan Surat Kehilangan.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">

<div class="card text-white bg-primary mb-3">
<div class="card-body">
<p>
    Dengan ini, saya seorang
        {% if object.kelamin|upper != "PEREMPUAN" %}
        Laki-Laki
        {% else %}
        Perempuan
        {% endif %}
     Bangsa
        {% if object.kebangsaan|upper != "WNA" %}
        Indonesia
        {% else %}
        Asing
        {% endif %}
        yang mengaku bernama:
</p>
<table>
    <tr>
        <td>Nama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nama|upper }}</td>
    </tr>
    <!-- Tempat dan Tanggal Lahir -->
    <tr>
        <td>Tempat tanggal lahir</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.tempat_lahir|upper }},
            {{ object.tanggal_lahir|date:"d F Y"|upper }}
        </td>
    </tr>
    <!-- Nomor Telpon -->
    <tr>
        <td>Nomor Telpon</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.nomor_telpon }}</td>
    </tr>
    <!-- Email -->
    <tr>
        <td>Alamat Email</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.email|upper }}</td>
    </tr>
    <!-- Agama -->
    <tr>
        <td>Agama</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.agama|upper }}</td>
    </tr>
    <!-- Pekerjaan -->
    <tr>
        <td>Pekerjaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.pekerjaan|upper }}</td>
    </tr>
    <!-- Kebangsaan -->
    <tr>
        <td>Kebangsaan</td>
        <td>&nbsp;:&nbsp;</td>
        <td>
            {% if object.kebangsaan != "WNA" %}
                INDONESIA
            {% else %}
                ASING
            {% endif %}

        </td>
    </tr>
    <!-- Alamat -->
    <tr>
        <td>Alamat</td>
        <td>&nbsp;:&nbsp;</td>
        <td>{{ object.alamat|upper }}</td>
    </tr>
    <tr>
        <td>
            &nbsp;
        </td>
        <td>
            &nbsp;
        </td>
        <td>{{ object.kota|upper }}</td>
    </tr>
</table>

<br>

<p>
Melaporkan telah kehilangan surat / barang berupa:
</p>

<p style="white-space: pre-line">
{{ object.jenis_barang_hilang|upper }}
{% if object.keterangan_kehilangan.strip %}
        {{ object.keterangan_kehilangan|safe }}
{% endif %}
</p>

<p>
Terjadi pada tanggal {{ object.tanggal_kehilangan|date:"d F Y" }} di {{ object.lokasi_kehilangan }}. Kerugian atas nama
    dan alamat tersebut di atas.
</p>

</div>
</div> <!-- Card -->

<br>
    <div id="pernyataan">
        <legend>Pernyataan:</legend>
        <label for="agree" class="form-check-label">
            <input id="agree" class="form-check-input" type="checkbox" value="agree" v-model="checked" title="Klik Saya">
            Dengan ini saya memastikan informasi yang saya berikan benar adanya.
        </label>
        <br>
        <br>
        <br>

<a href="{% url 'laporankehilanganuser:laporankehilanganuser-confirm' object.id %}"><button type="submit" class="btn btn-success btn-sm" :disabled="!checked">Kirim</button></a>
<a href="{% url 'laporankehilanganuser:laporankehilanganuser-update' object.id %}"><button type="submit" class="btn btn-info btn-sm">Sunting</button></a>
<a href="{% url 'laporankehilanganuser:laporankehilanganuser-delete' object.id %}"><button type="submit" class="btn btn-danger btn-sm">Batal</button></a>
   </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- Development Package of Vue
    <script src="http://vuejs.org/js/vue.js" type="text/javascript"></script>

    <script src="https://unpkg.com/vue@2.5.16/dist/vue.min.js" type="text/javascript"></script>
-->
    <script src="{% static "assets/js/bundle.js" %}" type="text/javascript"></script>
{% endblock %}